all: chct ct aoso2 aoso4 aoso6 kmp bndm bndmq2 bndmq4 bndmq6 bsdm bsdm2 bsdm3 bsdm4 sbndm2 sbndm sbndmq2 sbndmq4 bm ebom fbom hash3 hash5 hor hor4 hor8 hor16 shor4 shor8 shor16 sks4 sks8 sks16 ssk4 ssk8 ssk16
imp: chct ct sbndmq2 sbndmq4 sbndmq6 shor4 shor8 shor12 shor16 ssk4 ssk8 ssk12 ssk16
bfl:
	g++ source/bfl.c -std=c++11 -O3 -msse4 -lm -o bin/bfl
aoso2:
	g++ source/aoso2.c -std=c++11 -O3 -msse4 -lm -o bin/aoso2
aoso4:
	g++ source/aoso4.c -std=c++11 -O3 -msse4 -lm -o bin/aoso4
aoso6:
	g++ source/aoso6.c -std=c++11 -O3 -msse4 -lm -o bin/aoso6
kmp:
	g++ source/kmp.c -std=c++11 -O3 -msse4 -lm -o bin/kmp
bndm:
	g++ source/bndm.c -std=c++11 -O3 -msse4 -lm -o bin/bndm
bndmq2:
	g++ source/bndmq2.c -std=c++11 -O3 -msse4 -lm -o bin/bndmq2
bndmq4:
	g++ source/bndmq4.c -std=c++11 -O3 -msse4 -lm -o bin/bndmq4
bndmq6:
	g++ source/bndmq6.c -std=c++11 -O3 -msse4 -lm -o bin/bndmq6
bsdm:
	g++ source/bsdm.c -std=c++11 -O3 -msse4 -lm -o bin/bsdm
bsdm2:
	g++ source/bsdm2.c -std=c++11 -O3 -msse4 -lm -o bin/bsdm2
bsdm3:
	g++ source/bsdm3.c -std=c++11 -O3 -msse4 -lm -o bin/bsdm3
bsdm4:
	g++ source/bsdm4.c -std=c++11 -O3 -msse4 -lm -o bin/bsdm4
sbndm:
	g++ source/sbndm.c -std=c++11 -O3 -msse4 -lm -o bin/sbndm
sbndm2:
	g++ source/sbndm2.c -std=c++11 -O3 -msse4 -lm -o bin/sbndm2
sbndmq2:
	g++ source/sbndmq2.c -std=c++11 -O3 -msse4 -lm -o bin/sbndmq2
sbndmq4:
	g++ source/sbndmq4.c -std=c++11 -O3 -msse4 -lm -o bin/sbndmq4
sbndmq6:
	g++ source/sbndmq6.c -std=c++11 -O3 -msse4 -lm -o bin/sbndmq6
bm:
	g++ source/bm.c -std=c++11 -O3 -msse4 -lm -o bin/bm
ebom:
	g++ source/ebom.c -std=c++11 -O3 -msse4 -lm -o bin/ebom
fbom:
	g++ source/fbom.c -std=c++11 -O3 -msse4 -lm -o bin/fbom
ct:
	g++ source/ct.c -std=c++11 -O3 -msse4 -lm -o bin/ct
chct:
	g++ source/chct.c -std=c++11 -O3 -msse4 -lm -o bin/chct
hash3:
	g++ source/hash3.c -std=c++11 -O3 -msse4 -lm -o bin/hash3
hash5:
	g++ source/hash5.c -std=c++11 -O3 -msse4 -lm -o bin/hash5
hash8:
	g++ source/hash8.c -std=c++11 -O3 -msse4 -lm -o bin/hash8
hor:
	g++ source/hor.c -std=c++11 -O3 -msse4 -lm -o bin/hor
hor4:
	g++ source/hor4.c -std=c++11 -O3 -msse4 -lm -o bin/hor4
hor8:
	g++ source/hor8.c -std=c++11 -O3 -msse4 -lm -o bin/hor8
hor12:
	g++ source/hor12.c -std=c++11 -O3 -msse4 -lm -o bin/hor12
hor16:
	g++ source/hor16.c -std=c++11 -O3 -msse4 -lm -o bin/hor16
shor4:
	g++ source/shor4.c -std=c++11 -O3 -msse4 -lm -o bin/shor4
shor8:
	g++ source/shor8.c -std=c++11 -O3 -msse4 -lm -o bin/shor8
shor12:
	g++ source/shor12.c -std=c++11 -O3 -msse4 -lm -o bin/shor12
shor16:
	g++ source/shor16.c -std=c++11 -O3 -msse4 -lm -o bin/shor16
svm0:
	g++ source/svm0.c -std=c++11 -O3 -msse4 -lm -o bin/svm0
sks4:
	g++ source/sks4.c -std=c++11 -O3 -lm -o bin/sks4
sks8:
	g++ source/sks8.c -std=c++11 -O3 -lm -o bin/sks8
sks12:
	g++ source/sks12.c -std=c++11 -O3 -lm -o bin/sks12
sks16:
	g++ source/sks16.c -std=c++11 -O3 -lm -o bin/sks16
ssk4:
	g++ source/ssk4.c -std=c++11 -O3 -lm -o bin/ssk4
ssk8:
	g++ source/ssk8.c -std=c++11 -O3 -lm -o bin/ssk8
ssk12:
	g++ source/ssk12.c -std=c++11 -O3 -lm -o bin/ssk12
ssk16:
	g++ source/ssk16.c -std=c++11 -O3 -lm -o bin/ssk16
bmct:
	g++ source/bmct.c -std=c++11 -O3 -lm -o bin/bmct
pmct:
	g++ source/pmct.c -std=c++11 -O3 -msse4 -lm -o bin/pmct
bmhct:
	g++ source/bmhct.c -std=c++11 -O3 -lm -o bin/bmhct
horct:
	g++ source/horct.c -std=c++11 -O3 -lm -o bin/horct
